### ISSUE TITLE
Add screenshots in Readme

### ISSUE THREAD

**Issue by Sapphire64** [Alerion/fantasy_map#1]
See subj. Было бы неплохо иметь скриншоты, чтобы знать что и как уже работает :) удачи с проектом!

**Comment by Alerion** [comment]
Знаю, но только приступил к генератору. Пока как-то [так](https://www.dropbox.com/sh/okf4p1c6d0emc2i/AAAkJyzDFlalD6ZfV9ay8QeDa?dl=0&preview=Screenshot+from+2015-08-02+23%3A07%3A13.png) рендериться экспортированная карта с этого [демо](http://www-cs-students.stanford.edu/~amitp/game-programming/polygon-map-generation/demo.html).
